FROM pytorch/pytorch

WORKDIR /app
COPY --chmod=777 . .

# RUN conda env create -f whisper-mma.yml
# RUN conda activate whisper-mma
RUN python -m pip install --upgrade pip

RUN pip install -r requirements-gpu.txt
# RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
# RUN pip install pyannote.audio

EXPOSE 80
ENTRYPOINT ["python3", "app.py"]