FROM pytorch/pytorch

WORKDIR /app
COPY --chmod=777 . .

# RUN conda env create -f whisper-mma.yml
# RUN conda activate whisper-mma
# RUN python3 -m pip install --upgrade pip

RUN pip3 install -r requirements.txt
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip3 install pyannote.audio

EXPOSE 80
ENTRYPOINT ["python3", "app.py"]